### ISSUE TITLE
In 3D cases, are facets triangular facets?

### ISSUE THREAD

**Issue by wangxi0706** [tomilov/quickhull#12]
Elegant codes!

In 3D cases, are facets triangular facets?

**Comment by tomilov** [comment]
Hi, thanks. In 3D they are triangular

**Comment by wangxi0706** [comment]
> Hi, thanks. In 3D they are triangular

Thanks! It helps a lot.

**Comment by wangxi0706** [comment]
Another two questions:
1 Does the unit normal of facet point outward of the hull?
2 Is vertex order always anti-clock wise when seeing from outside the hull?

**Comment by tomilov** [comment]
1. You can find `distance` function. SIgned distances compared by value and there is sign checks, so normal should be oriented outwards.
2. Seems no, but really I don't remember. I pretty sure it should be possible to rewrite the algorithm in such a way, that this symmetry will be maintained at every intermediate step for free (in natural way). As I already mainained to do for `vertices_` and `neighbours_`. Such a symmetries come from Platonic world of Forms: (I believe) there is ideal way to implement the algorithm with many useful invariants right from the box.

**Comment by wangxi0706** [comment]
Thanks for your explanation!
