### ISSUE TITLE
Readme or make file would help

### ISSUE THREAD

**Issue by Akhila502** [tomilov/quickhull#9]
Hi there!! I am trying to look at how the code actually works but i'm facing issues as it is getting difficult without instructions on how to run the code or what input it expects.
Can anyone provide the inputs on the same.

**Comment by tomilov** [comment]
```cpp
#include <quickhull.hpp>

#include <limits>
#include <random>
#include <vector>

#include <cstdlib>

int main()
{
    using F = float;
    constexpr std::size_t dim = 3;
    using Points = std::vector<std::array<F, dim>>;

    Points points(10); // input

    { // fill it somehow (use real data)
        std::mt19937 gen;
        for (auto & [x, y, z] : points) {
            x = std::generate_canonical<F, std::numeric_limits<F>::digits>(gen);
            y = std::generate_canonical<F, std::numeric_limits<F>::digits>(gen);
            z = std::generate_canonical<F, std::numeric_limits<F>::digits>(gen);
        }
    }

    const auto eps = std::numeric_limits<F>::epsilon();
    quick_hull<typename Points::const_iterator> qh{dim, eps};
    qh.add_points(std::cbegin(points), std::cend(points));
    auto initial_simplex = qh.get_affine_basis();
    if (initial_simplex.size() < dim + 1) {
        return EXIT_FAILURE; // degenerated input set
    }
    qh.create_initial_simplex(std::cbegin(initial_simplex), std::prev(std::cend(initial_simplex)));
    qh.create_convex_hull();
    if (!qh.check()) {
        return EXIT_FAILURE; // resulted structure is not convex (generally due to precision errors)
    }

    qh.facets_; // use as result
}
```

**Comment by Akhila502** [comment]
cmake CMakeLists.txt
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:9 (message):
  only clang supported currently


-- Configuring incomplete, errors occurred!
************************************************************************************************************************8
How can we resolve this clang error

**Comment by tomilov** [comment]
You can use clang instead of gcc. Also you can remove that check from `CMakeLists.txt` I pretty sure.

**Comment by tomilov** [comment]
@Akhila502, please check it now.

**Comment by Akhila502** [comment]
Can I know till what dimensions you have tested?

**Comment by tomilov** [comment]
> Can I know till what dimensions you have tested?

I run many times at D10 during development (many years ago), but surely tried bigger. Due to nature of floating point numbers it is almost nonsense.
